version: "2.2"
services:
  controller:
    container_name: controller
    image: clixon/controller:${TAG}
    build:
      context: ../
      dockerfile: docker/Dockerfile
    ports:
      - "8082:80"
    volumes:
      - datastore:/usr/local/var/controller/
volumes:
  datastore:
