/*
 *
  ***** BEGIN LICENSE BLOCK *****

  Copyright (C) 2023 Olof Hagsand

  This file is part of CLIXON.

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.

  Alternatively, the contents of this file may be used under the terms of
  the GNU General Public License Version 3 or later (the "GPL"),
  in which case the provisions of the GPL are applicable instead
  of those above. If you wish to allow use of your version of this file only
  under the terms of the GPL, and not to allow others to
  use your version of this file under the terms of Apache License version 2, indicate
  your decision by deleting the provisions above and replace them with the
  notice and other provisions required by the GPL. If you do not delete
  the provisions above, a recipient may use your version of this file under
  the terms of any one of the Apache License version 2 or the GPL.

  ***** END LICENSE BLOCK *****

  * Common controller and custom definitions
  */

#ifndef _CONTROLLER_H
#define _CONTROLLER_H

/*
 * Constants
 */
#define CONTROLLER_PREFIX    "ctrl"
#define CONTROLLER_NAMESPACE "http://clicon.org/controller"

/*! Top-symbol in clixon datastores
 *
 * Duplicate of constant in clixon_custom.h
 */
#define DATASTORE_TOP_SYMBOL "config"

/*! Add extra sync pull state after commit
 *
 * This may be necessary if device changes from config from the one the controller has actually
 * pushed, see https://github.com/clicon/clixon-controller/issues/6
 * Alternatively, filter some fields not used so often
 */
#undef CONTROLLER_EXTRA_PUSH_SYNC

/*! netopeer/infix needs an extra namespace declaration in netconf lock/unlock
 */
#undef NETCONF_LOCK_EXTRA_NAMESPACE

/*! Keep actions datastore in memory, do not sync to file.
 *
 * In-mem is good for performance, but difficult to debug
 * Also may be unnecesary due to other optimizations
 * See also XMLDB_CANDIDATE_INMEM
 */
#define XMLDB_ACTION_INMEM 1

/*! Pyapi or other services process
 * Note this set also in clispec:s and tests
 */
#define SERVICES_PROCESS "Services process"

/*! Default top-level default-operation in outgoing NETCONF edit-config merge/replace/create messages
 *
 * Only for trees with merge/replace/create specific operations (not delete/remove)
 * (the controller separates adding and removing device nodes with two separate edit-config messages)
 * Some devices may not support "none" but requires "merge", such as JUNOS >= 24
 * Decided to set it to "merge" as default, although the correct is "none"
 * But for merge/replace/create as used in the controller, there should be no difference.
 */
#define NETCONF_EDIT_CONFIG_ADD_DEFAULT_OPERATION "merge"

/*! Controller debug levels
 */
#define CLIXON_DBG_CTRL CLIXON_DBG_APP
#define CLIXON_DBG_CTRL2 CLIXON_DBG_APP2

/*! Service (action)  timeout if service-timeout config is invalid in s */
#define CONTROLLER_SERVICE_TIMEOUT_DEFAULT 10

/*! Device state timeout if device-timeout config is invalid in s*/
#define CONTROLLER_DEVICE_TIMEOUT_DEFAULT 60

/*! Controller periodic timer for resoure handling in s */
#define CONTROLLER_PERIODIC_TIMER 60

/*
 * Global variables generated by Makefile
 */
extern const char CONTROLLER_BUILDSTR[];

#endif /* _CONTROLLER_H */
