name: Clixon Controller CI

on:
  push:
    branches:
      - main
      - test-actions
      - docker
  pull_request:
    branches:
      - main
  schedule:
    - cron: '00 3 * * 6'     # Run every Saturday morning

jobs:
  test-job:
    name: Controller tests
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v3
    - name: Copy Makefile # Kludge: use makefile.in so we dont need to run configure
      run: (cd docker && cp Makefile.in Makefile)
    - name: Build docker
      run: (cd docker; make docker)
    - name: Run tests
      run: (cd docker; make test)
