name: Clixon Controller CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
# 1) checkout and compile natively
    - name: install cligen native
      run: (git clone https://github.com/clicon/cligen.git && cd cligen && ./configure && make && sudo make install)
    - name: install ssl and nghttp2
      run: sudo apt install -y libssl-dev libnghttp2-dev
    - name: Add clixon user group
      run: sudo useradd -M -U clicon
    - name: Add runner to clixon user group
      run: sudo usermod -a -G clicon $(whoami)
    - name: Check group
      run: cat /etc/group|grep clicon
    - name: install clixon native
      run: (git clone https://github.com/clicon/clixon.git && cd clixon && ./configure && make && sudo make install)
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make install
      run: sudo make install
    - name: fix lib links
      run: sudo ldconfig
# 2)  Run tests
    - name: Start devices
      run: (cd test; ./start-devices.sh)
    - name: Start controller
      run: (cd test; ./init-controller.sh)
    - name: Change device config on controller and push to devices
      run: (cd test; INIT=false ./test-change-ctrl-push.sh)
#    - name: Change config on device and check diff
#      run: (cd test; ./test-change-device-diff.sh)
