name: Clixon Controller CI

on:
  push:
    branches:
      - main
      - test-actions
      - docker
  pull_request:
    branches:
      - main
  schedule:
    - cron: '00 3 * * 6'     # Run every Saturday morning

jobs:
  test-job:
    name: Controller tests
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v3
    - name: build clixon controller container
      run: (git clone https://github.com/clicon/clixon-controller.git && cd clixon-controller/docker/ && docker build -t clixon-controller .)
    - name: Run tests
      run: make test