name: Clixon Controller CI

on:
  push:
    branches:
      - main
      - test-actions
      - docker
      - tests_scaling
  pull_request:
    branches:
      - main
  schedule:
    - cron: '00 3 * * 6'     # Run every Saturday morning

jobs:
  test-job:
    name: Controller tests
    runs-on: ubuntu-latest
    timeout-minutes: 8
    steps:
    - uses: actions/checkout@v3
    - name: Clone controller code
      run: (cd docker; git clone ../ clixon-controller)
    - name: Start containers
      run: (cd docker; docker-compose up --build -d)
    - name: Run tests
      run: sleep 5; docker exec -t controller bash -c 'cd clixon-controller/test/;detail=true ./sum.sh'
